### ISSUE TITLE
Multi label application

### ISSUE THREAD

**Issue by DecentMakeover** [vandit15/Class-balanced-loss-pytorch#3]
Hey can this be applied to multi label problems?

Thanks

**Comment by goodluckcwl** [comment]
I think it can.

**Comment by DecentMakeover** [comment]
okay, ill try

**Comment by fcakyon** [comment]
@DecentMakeover feel free to use this improved/fixed/battle-tested version, supports multilabel loss calculation: https://github.com/fcakyon/balanced-loss#improvements
